name: CI

on:
 push:
  branches: [ main ]
  
defaults:
  run:
    working-directory: Code/backend
  

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2

    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: yarn install
      run: yarn install
      
    - name: yarn install
      run: yarn add typescript
      
    - name: typescript compile
      run: npx tsc

