name: CI

on:
 push:
  branches: [ main ]
  
defaults:
  run:
    working-directory: Code/backend
  

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2

    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install Yarn
      run: yarn install
      
    - name: Add Typescript
      run: yarn add typescript
      
    - name: Compile the Project
      run: npx tsc
      
    - name: Run the Tests
      run: npm test

    - name: Run the program
      run: npm start
    

